/**
 * Complaint Hooks - REFACTORED
 * Generated using createEntityHooks factory
 * 
 * Usage in components:
 * ```typescript
 * import { useComplaints, useComplaint } from '@/modules/features/complaints/hooks/useComplaints';
 * 
 * const ComplaintsPage = () => {
 *   const { data, isLoading, error } = useComplaints({ page: 1, limit: 10 });
 *   const { data: complaint } = useComplaint(complaintId);
 *   const createMutation = useCreateComplaint();
 *   const updateMutation = useUpdateComplaint();
 *   const deleteMutation = useDeleteComplaint();
 * };
 * ```
 */

import { createEntityHooks } from '@/hooks/factories/createEntityHooks';
import { complaintService } from '@/services/serviceFactory';
import { Complaint, ComplaintStats } from '@/types/complaints';
import { useQuery } from '@tanstack/react-query';

/**
 * Complaint hooks generated by factory
 */
const complaintHooks = createEntityHooks<Complaint>({
  entityName: 'Complaint',
  service: complaintService as any,
  queryKeys: {
    all: ['complaints'],
    list: () => ['complaints', 'list'],
    detail: (id: string) => ['complaints', id]
  },
  options: {
    staleTime: 5 * 60 * 1000, // 5 minutes
    retry: 2,
    showSuccessNotification: true,
    showErrorNotification: true
  }
});

/**
 * Hook: Get list of complaints with filtering and pagination
 */
export const useComplaints = complaintHooks.useEntities;

/**
 * Hook: Get single complaint by ID
 */
export const useComplaint = complaintHooks.useEntity;

/**
 * Hook: Create new complaint
 */
export const useCreateComplaint = complaintHooks.useCreateEntity;

/**
 * Hook: Update existing complaint
 */
export const useUpdateComplaint = complaintHooks.useUpdateEntity;

/**
 * Hook: Delete complaint
 */
export const useDeleteComplaint = complaintHooks.useDeleteEntity;

/**
 * Hook: Get complaint statistics
 * @deprecated Stats functionality should be moved to a separate service if needed
 */
export const useComplaintStats = () => {
  return useQuery({
    queryKey: ['complaints', 'stats'],
    queryFn: async () => {
      // TODO: Implement stats method in ComplaintService if needed
      return {
        total: 0,
        new: 0,
        inProgress: 0,
        closed: 0,
        byType: {
          breakdown: 0,
          preventive: 0,
          softwareUpdate: 0,
          optimize: 0
        },
        byPriority: {
          low: 0,
          medium: 0,
          high: 0,
          urgent: 0
        },
        avgResolutionTime: 0
      } as ComplaintStats;
    },
    staleTime: 10 * 60 * 1000
  });
};
