/**
 * Audit Log Hooks
 * Generated using createEntityHooks factory - REFACTORED
 * 
 * Usage in components:
 * ```typescript
 * import { useAuditLogs, useAuditLog } from '@/modules/features/audit-logs/hooks/useAuditLogs';
 * 
 * const LogsPage = () => {
 *   // Get paginated list
 *   const { data, isLoading, error } = useAuditLogs({ page: 1, limit: 10, search: 'login' });
 *   
 *   // Get single log
 *   const { data: log } = useAuditLog(logId);
 *   
 *   // Note: Create, update, delete are disabled for audit logs (immutable)
 * };
 * ```
 */

import { createEntityHooks } from '@/hooks/factories/createEntityHooks';
import { auditLogService } from '@/services/audit/supabase/AuditLogService';
import { AuditLog } from '@/types/audit';
import { QueryFilters } from '@/types/generic';

/**
 * Audit log hooks generated by factory
 */
const auditLogHooks = createEntityHooks<AuditLog>({
  entityName: 'Audit Log',
  service: auditLogService,
  queryKeys: {
    all: ['audit-logs'],
    list: (filters: QueryFilters) => ['audit-logs', 'list', JSON.stringify(filters || {})],
    detail: (id: string) => ['audit-logs', id]
  },
  options: {
    staleTime: 10 * 60 * 1000, // 10 minutes (audit logs don't change)
    retry: 2,
    showSuccessNotification: false, // No create/update/delete for audit logs
    showErrorNotification: true
  }
});

/**
 * Hook: Get list of audit logs with filtering, pagination, and search
 * 
 * @param filters Query filters (page, limit, search, customFilters)
 * @returns Query result with data, loading, error states
 */
export const useAuditLogs = auditLogHooks.useEntities;

/**
 * Hook: Get single audit log by ID
 * 
 * @param id Audit log ID
 * @returns Query result with audit log data
 */
export const useAuditLog = auditLogHooks.useEntity;

/**
 * Note: Create, update, delete hooks are not exported
 * Audit logs are immutable and can only be viewed, not modified
 */
